# Generated by Django 4.2.7 on 2023-12-12 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(max_length=64)),
                ('address', models.CharField(max_length=200)),
                ('contact_info', models.CharField(max_length=200)),
            ],
        ),
    ]
