# Generated by Django 4.2.7 on 2023-12-16 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='status',
            field=models.CharField(choices=[('donator', 'donator'), ('manager', 'manager')], default='manager', max_length=255),
        ),
    ]
