# Generated by Django 4.2.7 on 2023-12-16 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventName', models.CharField(max_length=255)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('org_information', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.info')),
            ],
        ),
    ]
