# Generated by Django 4.2.7 on 2023-12-16 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_alter_staff_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='desc',
            field=models.CharField(default=1, max_length=600),
            preserve_default=False,
        ),
    ]
