# Generated by Django 4.2.7 on 2023-12-16 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_alter_events_options_info_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='user_id',
        ),
    ]
