# Generated by Django 4.2.7 on 2023-12-16 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_events_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='desc',
            field=models.CharField(max_length=600, null=True),
        ),
    ]
